spring.application.name=finance-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=sneha120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true